### PR TITLE
fs: impl `File::read_exact_at` and `File::write_all_at`

### LINKED ISSUE #41: Impl `File::read_exact_at` and `File::write_all_at`
Same as [`std::io::Read::read_exact`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact) and [`std::io::Write::write_all`](https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all).

Here's my simple solution:
```rust
impl File {
    pub async fn read_exact_at<T: IoBufMut>(&self, mut buf: T, mut pos: u64) -> BufResult<(), T> {
        let mut bytes_read = 0;
        let buf_len = buf.bytes_init();
        while bytes_read < buf_len {
            let slice = buf.slice(bytes_read..);
            let (res, slice) = self.read_at(slice, pos).await;
            buf = slice.into_inner();
            match res {
                Ok(0) => {
                    return (
                        Err(io::Error::new(
                            io::ErrorKind::UnexpectedEof,
                            "failed to fill whole buffer",
                        )),
                        buf,
                    )
                }
                Ok(n) => {
                    bytes_read += n;
                    pos += n as u64;
                }
                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => {}
                Err(e) => return (Err(e), buf),
            };
        }

        (Ok(()), buf)
    }

    pub async fn write_all_at<T: IoBuf>(&self, mut buf: T, mut pos: u64) -> BufResult<(), T> {
        let mut bytes_written = 0;
        let buf_len = buf.bytes_init();
        while bytes_written < buf_len {
            let slice = buf.slice(bytes_written..);
            let (res, slice) = self.write_at(slice, pos).await;
            buf = slice.into_inner();
            match res {
                Ok(0) => {
                    return (
                        Err(io::Error::new(
                            io::ErrorKind::WriteZero,
                            "failed to write whole buffer",
                        )),
                        buf,
                    )
                }
                Ok(n) => {
                    bytes_written += n;
                    pos += n as u64;
                }
                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => {}
                Err(e) => return (Err(e), buf),
            };
        }

        (Ok(()), buf)
    }
}
```

### PR DESCRIPTION
**Pull request by songzhi**
Current API and abstractions make it possible to write these helper methods.

Fixes #41

### CODE REVIEW

File: src/fs/file.rs [hunk 1]
```diff
@@ -170,6 +170,89 @@ impl File {
...
+    /// ```
+    ///
+    /// [`ErrorKind::Interrupted`]: std::io::ErrorKind::Interrupted
+    /// [`ErrorKind::UnexpectedEof`]: std::io::ErrorKind::UnexpectedEof
+    pub async fn read_exact_at<T: IoBufMut>(
+        &self,
+        mut buf: T,
+        pos: u64,
+    ) -> crate::BufResult<(), T> {
+        let buf_len = buf.bytes_init();
```
Comment (carllerche) [inline src/fs/file.rs:228]: I think we want to use `bytes_total()` here to read in uninitialized memory? Though, this would change the API. E.g. passing in `Vec::with_capacity(100)` would read 100 bytes.

The `slice(..)` API could be used for limiting the length to read.

**Review by carllerche — CHANGES_REQUESTED** [review]
Looks good, thanks. I had one thought inline.

File: src/fs/file.rs (hunk 1 above)
Comment (songzhi) [reply src/fs/file.rs:228]: I did recognize that the `bytes_total()` instead of `bytes_init()` is used in the read operation in `tokio-uring`. But the `std::io::Read::read_exact`'s parameter is a `&mut [u8]`, whose length is immutable.
Maybe it's time to choose  consistency (in this crate) or conveyance  (between std and other libraries).
I think it's good to keep consistency in this crate and inform users the differences.

**Comment by tsturzl** [comment]
Just giving this a bump. I'm really interested in using the feature.

File: tests/fs_file.rs [hunk 2]
```diff
@@ -33,6 +40,17 @@ fn basic_read() {
     });
 }
 
+#[test]
```
Comment (Noah-Kennedy) [inline tests/fs_file.rs:43]: Might wanna try this with some really big generated array of bytes, possibly with something like quickcheck, just to be sure.

**Review by Noah-Kennedy — CHANGES_REQUESTED** [review]

**Review by Noah-Kennedy — APPROVED** [review]

File: src/fs/file.rs [hunk 3]
```diff
@@ -171,6 +171,89 @@ impl File {
...
+    /// ```
+    ///
+    /// [`ErrorKind::Interrupted`]: std::io::ErrorKind::Interrupted
+    /// [`ErrorKind::UnexpectedEof`]: std::io::ErrorKind::UnexpectedEof
+    pub async fn read_exact_at<T: IoBufMut>(
+        &self,
+        mut buf: T,
+        pos: u64,
+    ) -> crate::BufResult<(), T> {
+        let buf_len = buf.bytes_total();
```
Comment (jiangliu) [inline src/fs/file.rs:229]: Should we check for wrapping around of `buf_len + pos` here?

File: src/fs/file.rs [hunk 4]
```diff
@@ -222,6 +305,78 @@ impl File {
...
+    ///         file.close().await?;
+    ///         Ok(())
+    ///     })
+    /// }
+    /// ```
+    ///
+    /// [`write_at`]: File::write_at
+    /// [`ErrorKind::Interrupted`]: std::io::ErrorKind::Interrupted
+    pub async fn write_all_at<T: IoBuf>(&self, mut buf: T, pos: u64) -> crate::BufResult<(), T> {
+        let buf_len = buf.bytes_init();
```
Comment (jiangliu) [inline src/fs/file.rs:352]: validate `pos + buf_len` here too:)

File: src/fs/file.rs (hunk 3 above)
Comment (songzhi) [reply src/fs/file.rs:229]: Not sure about this, is there any similar checks in other functions?

File: src/fs/file.rs [hunk 5]
```diff
@@ -222,6 +316,89 @@ impl File {
...
+                            "failed to write whole buffer",
+                        )),
+                        buf,
+                    )
+                }
+                Ok(n) => {
+                    bytes_written += n;
+                }
+                Err(ref e) if e.kind() == io::ErrorKind::Interrupted => {}
+                Err(e) => return (Err(e), buf),
```
Comment (bnoordhuis) [inline src/fs/file.rs:395]: Drive-by review: wouldn't it be more appropriate to return success if `bytes_written > 0`? Returning an error means the caller loses track of how much data was written out. In some scenarios that might be a security liability.

Same line of reasoning applies to the `Ok(0)` case.

Comment (songzhi) [reply src/fs/file.rs:395]: It's same as `std::fs::File::write_all` implementation, so I don't think this is a problem.

**Review by littledivy — APPROVED** [review]

**Review by Noah-Kennedy — APPROVED** [review]

**Comment by Noah-Kennedy** [comment]
@songzhi can you resolve the conflicts? I'll merge once that's done.

**Review by Noah-Kennedy — APPROVED** [review]

File: tests/fs_file.rs (hunk 2 above)
Comment (FrankReh) [reply tests/fs_file.rs:36]: @Noah-Kennedy Is this still a concern?

File: src/fs/file.rs (hunk 3 above)
Comment (FrankReh) [reply src/fs/file.rs:348]: Let's resolve this unless someone has an example in std or tokio where such a wrap around check is made?

**Review by FrankReh — APPROVED** [review]
I'm going to say, let's try to get this committed. It's been out a long time.

File: src/fs/file.rs (hunk 1 above)
Comment (FrankReh) [reply src/fs/file.rs]: @carllerche Does the current form of the code satisfy your concern from Aug 2021?

**Comment by FrankReh** [comment]
@carllerche Waiting for your okay. You had requested changes so the page wants your blessing.

File: src/fs/file.rs (hunk 1 above)
Comment (FrankReh) [reply src/fs/file.rs]: @Noah-Kennedy Looking at the latest version of this code, it does use bytes_total() for the read and only the bytes_init() for the write. So I think the concern was taken to heart. Want to have this PR ignore a further review by @carllerche? Then it can be merged.
